services:
  elasticsearch:
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: password
  creator-search-nextjs:
    build:
      context: .
      dockerfile: docker/nextjs/Dockerfile
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_ELASTICSEARCH_URL: http://elasticsearch:9200
      NEXT_PUBLIC_ELASTICSEARCH_USERNAME: elastic
      NEXT_PUBLIC_ELASTICSEARCH_PASSWORD: password
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - elasticsearch

volumes:
  node_modules:
