import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import {
  Navbar,
  NavbarBrand,
  NavbarCollapse,
  NavbarLink,
  NavbarToggle,
} from 'flowbite-react'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar fluid rounded>
          <NavbarBrand as={Link} href='https://flowbite-react.com'>
            <span className='self-center whitespace-nowrap text-xl font-semibold dark:text-white'>
              ElasticSearchで飲食店検索
            </span>
          </NavbarBrand>
          <NavbarToggle />
          <NavbarCollapse>
            <NavbarLink as={Link} href='/'>
              飲食店検索
            </NavbarLink>
            <NavbarLink as={Link} href='/restaurants/register'>
              飲食店登録
            </NavbarLink>
          </NavbarCollapse>
        </Navbar>
        {children}
      </body>
    </html>
  )
}
